name: CI Back

on:
  push:
    # branches: [main, develop]
    branches: [chore/ci-cd-setup]
  pull_request:
    # branches: [main, develop]
    branches: [chore/ci-cd-setup]

jobs:
  test:
    name: Tests unitaires
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npx prisma generate
      - run: npm test

  typecheck:
    name: Vérification des types
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: npm
      - run: npm ci
      - run: npx prisma generate
      - run: npm run typecheck

  audit:
    name: Audit des dépendances
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 24
      - run: npm audit --audit-level=critical
